/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/x8APaxDrf0I
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
export function Nicaway() {
  return (
    (<div className="flex min-h-screen">
      <div className="w-1/2">
        <img
          src="/placeholder.svg"
          alt="Granada, Nicaragua"
          className="object-cover w-full h-full" />
        <div className="absolute top-4 right-4 w-8 h-8 rounded-full bg-white" />
      </div>
      <div
        className="flex flex-col justify-center w-1/2 p-8 bg-[#0072CE] text-white">
        <h1 className="mb-4 text-4xl font-bold">NicaWay</h1>
        <p className="mb-8 text-lg">Tu guía perfecta para el paraíso nicaragüense.</p>
        <form className="space-y-4">
          <div className="space-y-2">
            <label htmlFor="username" className="block text-sm">
              Nombre de usuario
            </label>
            <input
              type="text"
              id="username"
              className="w-full p-2 text-black rounded-md"
              placeholder="Nombre de usuario" />
          </div>
          <div className="space-y-2">
            <label htmlFor="password" className="block text-sm">
              Contraseña
            </label>
            <input
              type="password"
              id="password"
              className="w-full p-2 text-black rounded-md"
              placeholder="Contraseña" />
          </div>
          <button type="submit" className="w-full py-2 text-[#0072CE] bg-white rounded-md">
            Iniciar sesión
          </button>
        </form>
        <div className="my-4 text-center">o</div>
        <button
          className="flex items-center justify-center w-full py-2 mb-4 bg-black rounded-md">
          <ChromeIcon className="w-5 h-5 mr-2" />
          Inicia sesión con google
        </button>
        <p className="text-center">
          ¿No tienes una cuenta?{" "}
          <a href="#" className="font-bold underline">
            Regístrate
          </a>
        </p>
      </div>
    </div>)
  );
}

function ChromeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="4" />
      <line x1="21.17" x2="12" y1="8" y2="8" />
      <line x1="3.95" x2="8.54" y1="6.06" y2="14" />
      <line x1="10.88" x2="15.46" y1="21.94" y2="14" />
    </svg>)
  );
}
